/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Container: typeof import('./components/base/Container.vue')['default']
  const ProductSliced: typeof import('./components/home/ProductSliced.vue')['default']
  const useAuth: typeof import('./composables/useAuth')['useAuth']
  const useLoading: typeof import('./composables/useLoading')['default']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
}
